version: '3.8'

services:
    app:
        build:
            context: ./docker/php-fpm
            dockerfile: Dockerfile
        image: book-api-php
        container_name: book-api-php
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        networks:
            - app-network

    nginx:
        image: nginx:stable-alpine
        container_name: book-api-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: book-api-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql:/etc/mysql/conf.d
        networks:
            - app-network
        ports:
            - "3306:3306"

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
